# Generated by Django 5.1.5 on 2025-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notelogic", "0002_note_user_alter_note_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
